# Generated by Django 4.0.3 on 2022-05-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('stock_code', models.BigIntegerField(blank=True, null=True)),
                ('Invoice_no', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=400, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
