# Generated by Django 4.0.3 on 2022-06-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='stock_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
